---
substitutions:
  id: test-project

esphome:
  name: "${id}"
  name_add_mac_suffix: true

  project:
    name: wrboyce.test-project
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:
ota:
wifi:
  ap:
    password: "12345678"
captive_portal:
esp32_improv:
  authorizer: none
improv_serial:

dashboard_import:
  package_import_url: github://wrboyce/esphome-test-project/project-template-esp32.yaml@main

status_led:
  pin: GPIO32