name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: blackfin.yaml,blackfin-factory.yaml
      name: Project Blackfin
